### ISSUE TITLE
Data Feeds similar to GTFS

### ISSUE THREAD

**Issue by HiGregory** [openmobilityfoundation/cds-openapi#1]
Apparently, Philly is using CDS and would love to get access to their feeds or example. 

Is there a way for us to document Pilots of CDS API? See reference: https://twitter.com/Wheelmrk/status/1577018891255308288

**Comment by schnuerle** [comment]
Hi Greg. Yes as soon as cities/agencies make their CDS Curbs or Metrics endpoints public we will be sure to announce and document them on the Wiki here.

For now there are no public feeds as many are in the development phase. We will also amplify and report outs or press around CDS pilot and production projects! Join the [Curb mailing list](https://groups.google.com/a/openmobilityfoundation.org/g/wg-curb), attend our [public WG meetings](https://github.com/openmobilityfoundation/curb-data-specification/wiki#meeting-agendas), and see social media to follow along.
