### ISSUE TITLE
Update Stoplight landing page to not display default content

### ISSUE THREAD

**Issue by michael-danko-passport** [openmobilityfoundation/cds-openapi#4]
**Issue Summary**
The landing page for the [OMF homepage](https://openmobilityfnd.stoplight.io/) in Stoplight is still displaying the default boilerplate. This should be updated to reflect the OMF and link to any relevant resources.

**Context**
This is a file that can only be updated by a Stoplight Admin and is a Markdown file. Any images that need to be displayed can be embedded but will need to be hosted outside of the Stoplight tool. 

@schnuerle I believe you're the only one who has access to make these changes. If you have any text copy that you'd like to be displayed here, I can help write it but you will need to be the one who saves these changes.

**Comment by schnuerle** [comment]
Completed a first version of this page.
